### Data Mining: Homework 1 - R Implementation

#### Question 1:

Download the excel file ”UntidyData Badly-Structured-Sales-Dat.csv” from Teams and re- arrange this data into the correct four columns. There has been a mix of rows and columns everywhere. Also, watch out for Grand Totals and Sub Totals, you do not need those in tidy data.

In [2]:
# loading tidy verse
library(tidyverse)
library(readxl)
library(conflicted)

The next step is to read the dataset into a dataframe or `tibble` before exploration and preprocessing.

In [3]:
data = read_excel('Data/UntidyData_Badly-Structured-Sales-Dat.xlsx')
head(data)

New names:
• `` -> `...3`
• `` -> `...4`
• `` -> `...5`
• `` -> `...8`
• `` -> `...9`
• `` -> `...10`
• `` -> `...13`
• `` -> `...14`
• `` -> `...15`

  Segment>>      Consumer    ...3     ...4         ...5
1 Ship Mode>>    First Class Same Day Second Class Standard Class
2 Order ID       NA          NA       NA           NA
3 CA-2011-100293 NA          NA       NA           NA
4 CA-2011-100706 NA          NA       129.44       NA
5 CA-2011-100895 NA          NA       NA           605.47
6 CA-2011-100916 NA          NA       NA           NA
  Consumer Total Corporate   ...8     ...9         ...10
1     NA         First Class Same Day Second Class Standard Class
2     NA         NA          NA       NA           NA
3     NA         NA          NA       NA           NA
4 129.44         NA          NA       NA           NA
5 605.47         NA          NA       NA           NA
6     NA         NA          NA       NA           788.86
  Corporate Total Home Office ...13    ...14        ...15
1     NA          First Class Same Day Second Class Standard Class
2     NA          NA          NA       NA           NA
3     NA          NA          NA       NA           91.055999999999997
4     NA          NA          NA       NA           NA
5     NA          NA          NA       NA           NA
6 788.86          NA          NA       NA           NA
  Home Office Total
1     NA
2     NA
3 91.056
4     NA
5     NA
6     NA

<br>

Right away, we see a potential issue with column names. Let's look at the column names more closely.

In [4]:
colnames(data)

 [1] "Segment>>"         "Consumer"          "...3"
 [4] "...4"              "...5"              "Consumer Total"
 [7] "Corporate"         "...8"              "...9"
[10] "...10"             "Corporate Total"   "Home Office"
[13] "...13"             "...14"             "...15"
[16] "Home Office Total"

We notice that the columns names are given in human readable form, noting that they repeat themselves in specific intervals.

#### 1. Create New Column Names

We can now create new column names using the `rep` function that we will use later.

In [5]:
column_names = c(('Segment'), rep( c('Consumer', 'Corporate', 'Home Office'), times = 1, each = 4))
column_names

 [1] "Segment"     "Consumer"    "Consumer"    "Consumer"    "Consumer"
 [6] "Corporate"   "Corporate"   "Corporate"   "Corporate"   "Home Office"
[11] "Home Office" "Home Office" "Home Office"

### 2. TidyVerse Implementation

To implement tidyverse sequence, we need to run the following operations.

1. Drop Columns and rows with `Totals` Informatiom
2. Replace the column names with column names above
3. Combine First Row and Newly Created Columns
4. Implement a `pivot_longer` method
5. Separate Order Type and Class Columns
6. Remove Earlier Misclassification/Pivot Long
7. Drop NAs

In [6]:
data %>% select( -c('Consumer Total', 'Corporate Total', 'Home Office Total') ) %>%     # Dropping total columns 
         dplyr::filter( !row_number() %in% c(1, nrow(.)) ) %>%                                 # Drops the last row containing Total values and the First Column
         set_names(., paste(column_names, data[1, -c(6, 11, 16)], sep = ',' ) ) %>%     # Combine First Row and Newly Created Columns
         pivot_longer( cols = !1 , names_to = 'OrderType', values_to = 'Value') %>%     # Implement Pivot Longer
         separate(col = OrderType, into = c('OrderType', "Class"), sep = ",") %>%       # Separate Order Type and Class Columns
         dplyr::filter( !row_number() %in% c(1:12) ) %>%                                       # Remove Earlier Misclassification/Pivot Long
         drop_na() %>%                                                                  # Drop NAs
         set_names( c('OrderID', 'OrderType', 'Class', 'OrderValue') )                  # Set Column Names

    OrderID        OrderType   Class          OrderValue
1   CA-2011-100293 Home Office Standard Class 91.055999999999997
2   CA-2011-100706 Consumer    Second Class   129.44
3   CA-2011-100895 Consumer    Standard Class 605.47
4   CA-2011-100916 Corporate   Standard Class 788.86
5   CA-2011-101266 Consumer    Second Class   13.36
6   CA-2011-101560 Corporate   Second Class   542.34
7   CA-2011-101770 Corporate   Standard Class 1.869
8   CA-2011-102274 Corporate   Standard Class 865.5
9   CA-2011-102673 Corporate   Standard Class 1044.44
10  CA-2011-102988 Corporate   Second Class   4251.92
11  CA-2011-103317 Corporate   First Class    242.54599999999999
12  CA-2011-103366 Consumer    First Class    149.94999999999999
13  CA-2011-103807 Corporate   Standard Class 21.19
14  CA-2011-103989 Corporate   First Class    590.76199999999994
15  CA-2011-104283 Consumer    Standard Class 616.14
16  CA-2011-106054 Corporate   First Class    12.78
17  CA-2011-106810 Corporate   Standard Class 310.88
18  CA-2011-107573 Consumer    Standard Class 23.472000000000001
19  CA-2011-107811 Corporate   Standard Class 661.50400000000002
20  CA-2011-108707 Home Office Standard Class 10.368
21  CA-2011-109043 Consumer    First Class    243.6
22  CA-2011-109232 Consumer    Second Class   545.94000000000005
23  CA-2011-110100 Consumer    Standard Class 302.37599999999998
24  CA-2011-110408 Corporate   Second Class   2216.8000000000002
25  CA-2011-110422 Consumer    Second Class   25.248000000000001
26  CA-2011-111500 Corporate   Standard Class 484.79
27  CA-2011-111934 Corporate   First Class    47.32
28  CA-2011-112718 Corporate   Standard Class 1.167
29  CA-2011-113047 Consumer    Same Day       11.85
30  CA-2011-113166 Consumer    First Class    9.5679999999999996
⋮   ⋮              ⋮           ⋮              ⋮
793 US-2014-132297 Home Office Standard Class 598.30999999999995
794 US-2014-132675 Home Office Standard Class 148.16
795 US-2014-133781 Consumer    First Class    37.607999999999997
796 US-2014-134642 Consumer    Standard Class 428.70400000000001
797 US-2014-135062 Consumer    Second Class   229.54400000000001
798 US-2014-135503 Corporate   Standard Class 14.76
799 US-2014-135986 Consumer    Standard Class 536.36
800 US-2014-136189 Consumer    Standard Class 82.38
801 US-2014-146822 Consumer    Standard Class 49.12
802 US-2014-146878 Consumer    Standard Class 12.294
803 US-2014-148768 Home Office Second Class   71.975999999999999
804 US-2014-148831 Consumer    First Class    348.56
805 US-2014-149510 Consumer    Standard Class 98.445999999999998
806 US-2014-152492 Consumer    Same Day       239.24
807 US-2014-152842 Consumer    Standard Class 242.352
808 US-2014-152898 Consumer    Standard Class 67.900000000000006
809 US-2014-153633 Consumer    Second Class   2.0640000000000001
810 US-2014-156083 Home Office Standard Class 9.6639999999999997
811 US-2014-158526 Consumer    Second Class   1814.68
812 US-2014-159205 Home Office Second Class   732.93
813 US-2014-162208 Corporate   First Class    2.8959999999999999
814 US-2014-162558 Home Office First Class    2437.672
815 US-2014-162670 Corporate   Second Class   1152.8699999999999
816 US-2014-163195 Consumer    Second Class   29.16
817 US-2014-165953 Consumer    Standard Class 71.096000000000004
818 US-2014-166233 Consumer    Standard Class 24
819 US-2014-166611 Corporate   Standard Class 68.742000000000004
820 US-2014-167920 Consumer    Second Class   1827.51
821 US-2014-168116 Corporate   Same Day       8167.42
822 US-2014-168690 Consumer    Standard Class 2.8079999999999998

<br>

### Question 2.


Download the excel file ”UntidyInvoices-with-Merged-Categories-and-Merged-Amounts.csv” from Teams and tidy it. Because a single transaction (identified with an order id ) has multiple items purchased, who ever captured this data decided to create a single row for each order, thereby lumping the different items purchased and the amounts together into 2 fields respectively. The better thing to do is to let each item purchased be on a single row with the amount. It is better to repeat the Order IDs on different rows than lumping up amounts in a single cell. As we will be analyzing items bought and amounts a lot, we need them separated into rows.

In [7]:
invoices = read_excel('Data//UntidyInvoices-with-Merged-Categories-and-Merged-Amounts.xlsx')
head(invoices)

  Order ID       Category
1 CA-2011-167199 Binders | Art | Phones | Fasteners | Paper
2 CA-2011-149020 Office Supplies | Furniture
3 CA-2011-131905 Office Supplies | Technology | Technology
4 CA-2011-127614 Accessories | Tables | Binders
  Amount
1 609.98 | 5.48 | 391.98 | 755.96 | 31.12
2 2.98 | 51.94
3 7.2 | 42.0186 | 42.035
4 234.45 | 1256.22 | 17.46

<br>

#### Solution

For this problem, I implement the method `separate_longer_delim` which splits columns by a separator.

In [8]:
invoices %>% separate_longer_delim(c("Category", "Amount"), delim = "|")

   Order ID       Category         Amount
1  CA-2011-167199 Binders          609.98
2  CA-2011-167199  Art              5.48
3  CA-2011-167199  Phones           391.98
4  CA-2011-167199  Fasteners        755.96
5  CA-2011-167199  Paper            31.12
6  CA-2011-149020 Office Supplies  2.98
7  CA-2011-149020  Furniture        51.94
8  CA-2011-131905 Office Supplies  7.2
9  CA-2011-131905  Technology       42.0186
10 CA-2011-131905  Technology       42.035
11 CA-2011-127614 Accessories      234.45
12 CA-2011-127614  Tables           1256.22
13 CA-2011-127614  Binders          17.46